# Generated by Django 5.1.7 on 2025-03-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('status', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=50)),
                ('continent_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=5)),
                ('region', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(max_length=100)),
                ('offset', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('isp', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('as_number', models.CharField(max_length=50)),
                ('as_name', models.CharField(max_length=100)),
                ('mobile', models.BooleanField()),
                ('proxy', models.BooleanField()),
                ('hosting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=10)),
                ('action', models.CharField(choices=[('PASS', 'Pass'), ('BLOCK', 'Block'), ('REJECT', 'Reject')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_rules', to='rules.destinationmetadata')),
            ],
        ),
    ]
