# Generated by Django 5.1.7 on 2025-03-21 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
                ('interface', models.CharField(blank=True, max_length=50)),
                ('source_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField()),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='firewallrule',
            old_name='timestamp',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='destinationmetadata',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationmetadata',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='destinationmetadata',
            unique_together={('ip', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='firewallrule',
            unique_together={('destination_ip', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='destinationmetadata',
            index=models.Index(fields=['ip'], name='rules_desti_ip_240b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationmetadata',
            index=models.Index(fields=['ip', 'end_date'], name='rules_desti_ip_2e474d_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrule',
            index=models.Index(fields=['destination_ip'], name='rules_firew_destina_68a53e_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrule',
            index=models.Index(fields=['destination_ip', 'start_date', 'end_date'], name='rules_firew_destina_c5af13_idx'),
        ),
        migrations.AddField(
            model_name='devicemac',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_addresses', to='rules.device'),
        ),
        migrations.AddField(
            model_name='deviceip',
            name='mac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_assignments', to='rules.devicemac'),
        ),
        migrations.AddField(
            model_name='firewalllog',
            name='destination_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='rules.destinationmetadata'),
        ),
        migrations.AddIndex(
            model_name='devicemac',
            index=models.Index(fields=['mac_address'], name='rules_devic_mac_add_390ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemac',
            index=models.Index(fields=['mac_address', 'start_date', 'end_date'], name='rules_devic_mac_add_414091_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemac',
            unique_together={('mac_address', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='deviceip',
            index=models.Index(fields=['ip_address'], name='rules_devic_ip_addr_a93b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceip',
            index=models.Index(fields=['mac', 'start_date', 'end_date'], name='rules_devic_mac_id_a40887_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceip',
            unique_together={('mac', 'ip_address', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='firewalllog',
            unique_together={('timestamp', 'source_ip', 'destination_ip', 'source_port', 'destination_port')},
        ),
    ]
