# Generated by Django 5.1.7 on 2025-03-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_device_deviceip_devicemac_firewalllog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmetadata',
            name='dns_name',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
