# Generated by Django 5.1.7 on 2025-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_destinationmetadata_dns_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmetadata',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
