# Generated by Django 5.1.7 on 2025-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_destinationmetadata_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmetadata',
            name='as_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='as_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='continent_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='dns_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='hosting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='isp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='mobile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationmetadata',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
