# Generated by Django 5.1.7 on 2025-03-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_destinationmetadata_as_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAllowedISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_name', models.CharField(max_length=100)),
                ('allowed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_isps', to='rules.device')),
            ],
            options={
                'indexes': [models.Index(fields=['isp_name'], name='rules_devic_isp_nam_2c3636_idx'), models.Index(fields=['device', 'allowed'], name='rules_devic_device__a488fd_idx')],
                'unique_together': {('device', 'isp_name')},
            },
        ),
    ]
