# Generated by Django 5.1.7 on 2025-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_deviceallowedisp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deviceallowedisp',
            name='rules_devic_device__a488fd_idx',
        ),
        migrations.RemoveField(
            model_name='deviceallowedisp',
            name='allowed',
        ),
        migrations.AddIndex(
            model_name='deviceallowedisp',
            index=models.Index(fields=['device', 'isp_name'], name='rules_devic_device__6424fd_idx'),
        ),
    ]
