# Generated by Django 5.1.7 on 2025-03-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_remove_deviceallowedisp_rules_devic_device__a488fd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedDeviceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('ip_address', 'mac_address')},
            },
        ),
    ]
