# Generated by Django 5.1.7 on 2025-03-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_unapproveddeviceentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unapproveddeviceentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='unapproveddeviceentry',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='unapproveddeviceentry',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
