# Generated by Django 5.1.7 on 2025-03-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_alter_unapproveddeviceentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('lease_start', models.DateTimeField()),
                ('lease_end', models.DateTimeField()),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('interface', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rules.device')),
            ],
        ),
        migrations.DeleteModel(
            name='UnapprovedDeviceEntry',
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['mac_address', 'ip_address'], name='rules_devic_mac_add_b7a2f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicelease',
            unique_together={('ip_address', 'mac_address', 'lease_start')},
        ),
    ]
