# Generated by Django 5.1.7 on 2025-03-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_devicelease_delete_unapproveddeviceentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelease',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rules.device'),
        ),
    ]
