# Generated by Django 5.1.7 on 2025-04-04 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_alter_devicelease_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='isp_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='pushed_to_opnsense',
            field=models.BooleanField(default=False),
        ),
    ]
