# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_firewallrule_created_at_firewallrule_isp_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='pushed_to_opnsense',
        ),
    ]
