# Generated by Django 5.1.7 on 2025-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_remove_firewallrule_pushed_to_opnsense'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dns_description',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare (1.1.1.1)'), ('google', 'Google (8.8.8.8)'), ('quad9', 'Quad9 (9.9.9.9)')], default='cloudflare', max_length=20),
        ),
    ]
