# Generated by Django 5.1.7 on 2025-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_device_dns_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dns_description',
        ),
        migrations.AddField(
            model_name='device',
            name='dns_server',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare (1.1.1.1)'), ('google', 'Google (8.8.8.8)'), ('quad9', 'Quad9 (9.9.9.9)')], default='quad9', max_length=20),
        ),
    ]
