# Generated by Django 5.1.7 on 2025-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_remove_device_dns_description_device_dns_server'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicemac',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='devicemac',
            name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='dns_server',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare (1.1.1.1)'), ('google', 'Google (8.8.8.8)'), ('quad9', 'Quad9 (9.9.9.9)')], default='cloudflare', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeviceIp',
        ),
        migrations.DeleteModel(
            name='DeviceMac',
        ),
    ]
