# Generated by Django 5.1.7 on 2025-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_alter_devicemac_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmetadata',
            name='console_first_output',
            field=models.BooleanField(default=False),
        ),
    ]
