# Generated by Django 5.1.7 on 2025-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_destinationmetadata_console_first_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='examiner',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
