# Generated by Django 5.1.7 on 2025-04-11 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0019_device_archived_device_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
