# Generated by Django 5.1.7 on 2025-04-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0022_destinationmetadata_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationmetadata',
            name='console_first_output',
        ),
        migrations.CreateModel(
            name='MetadataSeenByDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.device')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.destinationmetadata')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'metadata'], name='rules_metad_device__a2fd28_idx')],
                'unique_together': {('device', 'metadata')},
            },
        ),
    ]
