# Generated by Django 5.1.7 on 2025-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0023_remove_destinationmetadata_console_first_output_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataseenbydevice',
            old_name='seen_at',
            new_name='first_seen_at',
        ),
        migrations.AddField(
            model_name='metadataseenbydevice',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
