# Generated by Django 5.1.7 on 2025-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0024_rename_seen_at_metadataseenbydevice_first_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
