# Generated by Django 5.1.7 on 2025-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0025_firewallrule_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='dns',
            field=models.BooleanField(default=False),
        ),
    ]
