# Generated by Django 5.1.7 on 2025-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0026_firewallrule_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelease',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
