# Generated by Django 5.1.7 on 2025-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0027_devicelease_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_active',
        ),
        migrations.AlterField(
            model_name='device',
            name='examiner',
            field=models.CharField(max_length=20),
        ),
    ]
