# Generated by Django 5.1.7 on 2025-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0028_remove_device_last_active_alter_device_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataseenbydevice',
            name='last_seen_at',
            field=models.DateTimeField(),
        ),
    ]
