# Generated by Django 5.1.7 on 2025-05-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0029_alter_metadataseenbydevice_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='rules.device'),
        ),
        migrations.AlterUniqueTogether(
            name='devicelease',
            unique_together={('ip_address', 'mac_address')},
        ),
    ]
