# Generated by Django 5.1.7 on 2025-05-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0030_firewallrule_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='rules.device'),
        ),
    ]
