# Generated by Django 5.1.7 on 2025-05-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0031_alter_firewallrule_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
