# Generated by Django 5.1.7 on 2025-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0032_firewallrule_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='verify_opnsense',
            field=models.BooleanField(default=False),
        ),
    ]
