# Generated by Django 5.1.7 on 2025-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0033_firewallrule_verify_opnsense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
