# Generated by Django 5.1.7 on 2025-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0034_alter_firewallrule_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='uuid',
            field=models.CharField(max_length=50),
        ),
    ]
