# Generated by Django 5.1.7 on 2025-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_alter_firewallrule_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('query_type', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=255)),
                ('resolved_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_line', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='dns_server',
            field=models.CharField(choices=[('local', 'local (192.168.5.1)'), ('cloudflare', 'Cloudflare (1.1.1.1)'), ('google', 'Google (8.8.8.8)'), ('quad9', 'Quad9 (9.9.9.9)')], default='local', max_length=20),
        ),
    ]
