# Generated by Django 5.1.7 on 2025-05-30 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0036_dnsrecord_alter_device_dns_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='last_seen_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
