# Generated by Django 5.1.7 on 2025-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0037_dnsrecord_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(),
        ),
    ]
