# Generated by Django 5.1.7 on 2025-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0038_alter_device_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dns_server',
            field=models.CharField(choices=[('local', 'local (192.168.5.1)')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
